#!/bin/bash

# Configuration
SESSION_NAME="genaigrader"
PROJECT_DIR="/home/joaquin/genaigrader-jentrialgo"
GUNICORN_PID_FILE="$PROJECT_DIR/gunicorn.pid"
ENV_FILE="$PROJECT_DIR/.env.django"
GUNICORN_APP="mi_web.wsgi:application"
GUNICORN_SOCKET="127.0.0.1:9898"
SETTINGS_MODULE="mi_web.settings_ngrok"
LOGFILE="gunicorn.log"

# Stop gunicorn if running
if [ -f "$GUNICORN_PID_FILE" ]; then
    PID=$(cat "$GUNICORN_PID_FILE")
    echo "🛑 Stopping gunicorn (PID: $PID)..."
    kill $PID && rm -f "$GUNICORN_PID_FILE"
    echo "✅ Gunicorn stopped."
    sleep 2
else
    echo "ℹ️ Gunicorn PID not found. Attempting to pkill gunicorn..."
    pkill gunicorn
fi

# Reload environment and restart gunicorn inside tmux session
echo "🚀 Restarting gunicorn in tmux session '$SESSION_NAME'..."

tmux has-session -t "$SESSION_NAME" 2>/dev/null
if [ $? != 0 ]; then
    echo "❌ Tmux session '$SESSION_NAME' not found. Please run start_genaigrader.sh first."
    exit 1
fi

echo "📦 Collecting static files..."
cd $PROJECT_DIR
set -a; source $ENV_FILE; set +a
uv run python manage.py collectstatic --noinput --clear

# Retrieve public ngrok URL
for i in {1..10}; do
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.name=="backend") | .public_url' | sed 's|https://||; s|http://||')
    if [[ -n "$NGROK_URL" ]]; then
        echo "✅ ngrok public URL: $NGROK_URL"
        break
    fi
    sleep 1
done

if [[ -z "$NGROK_URL" ]]; then
    echo "❌ Could not get ngrok public URL."
    exit 1
fi

# Write env variables to be sourced
cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by scripts/start_genaigrader.sh — DO NOT EDIT MANUALLY.
# Your changes will be overwritten on the next run.
# To add persistent variables, edit .env.django.base instead.
export DJANGO_ALLOWED_HOSTS="$NGROK_URL,localhost"
EOF
cat "$PROJECT_DIR/.env.django.base" >> "$ENV_FILE"

# Send commands to tmux to restart gunicorn
tmux send-keys -t "$SESSION_NAME" "cd $PROJECT_DIR" C-m
tmux send-keys -t "$SESSION_NAME" "set -a; source $ENV_FILE; set +a" C-m
tmux send-keys -t "$SESSION_NAME" "uv run gunicorn $GUNICORN_APP \
    --bind $GUNICORN_SOCKET \
    --log-file $LOGFILE \
    --pid gunicorn.pid \
    --timeout 6000 \
    --env DJANGO_SETTINGS_MODULE=$SETTINGS_MODULE > debug_output.log 2>&1 &" C-m

# Stop and restart qcluster
pkill -f "manage.py qcluster" 2>/dev/null
sleep 1

# Reuse existing qcluster pane if it exists, otherwise create a new split.
WORKER_PANE="${SESSION_NAME}.1"
if tmux has-session -t "$WORKER_PANE" 2>/dev/null; then
    tmux send-keys -t "$WORKER_PANE" C-c
    tmux send-keys -t "$WORKER_PANE" "cd $PROJECT_DIR" C-m
    tmux send-keys -t "$WORKER_PANE" "set -a; source $ENV_FILE; set +a" C-m
    tmux send-keys -t "$WORKER_PANE" "uv run manage.py qcluster --settings=$SETTINGS_MODULE" C-m
else
    tmux split-window -t "$SESSION_NAME" -v
    tmux send-keys -t "$SESSION_NAME" "cd $PROJECT_DIR" C-m
    tmux send-keys -t "$SESSION_NAME" "set -a; source $ENV_FILE; set +a" C-m
    tmux send-keys -t "$SESSION_NAME" "uv run manage.py qcluster --settings=$SETTINGS_MODULE" C-m
fi

echo "✅ Gunicorn + qcluster restart sent to tmux session '$SESSION_NAME'."
